version: "3.9"
services:
  postgres-db:
    image: postgres:13.5
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracking_build
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

